import = [
  "/home/shun/.local/share/pnpm/global/5/.pnpm/alacritty-themes@6.0.2/node_modules/alacritty-themes/themes/github_dark.toml",
]

[env]
TERM = "rxvt-256color"

[font]
size = 14

[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"

[font.bold]
family = "JetBrainsMono NFM"
style = "Regular"

[font.italic]
family = "JetBrainsMono NFM"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono NFM"
style = "Regular Italic"

[font.offset]
x = 0
y = 4

[cursor.style]
shape = "Beam"
blinking = "On"

[[mouse.bindings]]
mouse = "Middle"
mode = "~Vi"
action = "PasteSelection"

[[keyboard.bindings]]
key = "Space"
mods = "Control"
mode = "~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "J"
mods = "Control"
action = "ScrollHalfPageDown"

[[keyboard.bindings]]
key = "J"
mods = "Shift"
mode = "Vi|~Search"
action = "ScrollHalfPageDown"

[[keyboard.bindings]]
key = "K"
mods = "Control"
action = "ScrollHalfPageUp"

[[keyboard.bindings]]
key = "K"
mods = "Shift"
mode = "Vi|~Search"
action = "ScrollHalfPageUp"
